name: 打包项目
on:
  workflow_dispatch:
    inputs:
        build:
            description: '选择要构建的文件编号'
            required: true
            default: 'true'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          directories=""
          for dir in $(ls -d */); do
          directories="$directories ${dir%/}"
          echo "DIRECTORY_NAMES=$directories"
          done
